//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.10 at 10:15:49 PM COT 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="asesor" type="{http://spring.io/guides/gs-producing-web-service}asesor"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "asesor"
})
@XmlRootElement(name = "updateAsesorRequest")
public class UpdateAsesorRequest {

    @XmlElement(required = true)
    protected Asesor asesor;

    /**
     * Gets the value of the asesor property.
     * 
     * @return
     *     possible object is
     *     {@link Asesor }
     *     
     */
    public Asesor getAsesor() {
        return asesor;
    }

    /**
     * Sets the value of the asesor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asesor }
     *     
     */
    public void setAsesor(Asesor value) {
        this.asesor = value;
    }

}
